### ISSUE TITLE
Diseño arquitectónico

### ISSUE THREAD

**Issue by jfm1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#18]

**Comment by drg1006** [comment]
Se añade un commint que referencia a este Issue.
Document Diseno Arquitectonico #18

**Comment by drg1006** [comment]
Se añade un commint que referencia a este Issue.
Add references #18

**Comment by drg1006** [comment]
Se añade un commint que referencia a este Issue.
Improve Dieseno Arquitectonico documentation #18
