### ISSUE TITLE
Diseño de interfaces

### ISSUE THREAD

**Issue by jfm1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#20]

**Comment by drg1006** [comment]
Se añade un commit que referencia a este issue.
Docmuent Diseno de Interfaces #20

**Comment by drg1006** [comment]
Se añade un commit que referencia a este issue.
Minor fix #20

**Comment by drg1006** [comment]
Se añade un commit que referencia a este issue.
Minor fix #20
