### ISSUE TITLE
Pasar memoria doc a latex

### ISSUE THREAD

**Issue by drg1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#22]
- Revisar imágenes.
- Revisar bibliografía.
- bibentry (http://gking.harvard.edu/files/bibentry2.pdf).

**Documentación**

- [x]  Resumen
- [x]  Introducción
- [x]  Objetivos del proyecto
- [x]  Conceptos teóricos
- [x]  Técnicas y herramientas
- [x]  Aspectos relevantes
- [x]  Trabajos relacionados
- [x]  Conclusiones y Líneas de trabajo futuras

**Comment by jfm1006** [comment]
changed the pipeline from New Issues to TODO for Untitled - 167943 - 2016-08-17 on 31 Dec 2016

**Comment by jfm1006** [comment]
Expresión regular para corregir las referencias:

Buscar: (\{\[\})([\w:\\]+)(\{\]\}\\\_)
Reemplazar por: \\citep{\2}
Ej: {[}art:campbell2005{]}\_ -> \citep{art:campbell2005}

**Comment by jfm1006** [comment]
Expresión regular para corregir las referencias:

- Buscar: (\{\[\})([\w:\\]+)(\{\]\}\\\_)
- Reemplazar por: \\citep{\2}

Ej: {[}art:campbell2005{]}\_ -> \citep{art:campbell2005}

**Comment by jfm1006** [comment]
Expresión regular para corregir las imágenes:

- Buscar: (\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})
- Reemplazar por: \\imagen{\2}{descripción...}

Ej: \includegraphics{../../img/s2.png} -> \imagen{s2}{descripción...}}

**Comment by jfm1006** [comment]
**Cheat-sheet plantilla**
**Rutas de ficheros / paquetes**
\ruta{C:/Windows/System32}
**Imágenes**
Imagen en el sitio introducido:

\imagen{nombre-img}{Descripción...}
Imagen flotante:

\imagenflotante{nombre-img}{Descripción...}
El nombre de la imagen sin extensión.

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 25 Jan 2017
Convert to latex points 1 and 2

**Comment by jfm1006** [comment]
changed the pipeline from TODO to In Progress for Untitled - 167943 - 2016-08-17 on 26 Jan 2017

**Comment by jfm1006** [comment]
changed the title Pasar doc a latex Pasar memoria doc a latex on 26 Jan 2017

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 27 Jan 2017
Convert to latex point 4

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 28 Jan 2017
Convert to latex point 5

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 28 Jan 2017
Convert to latex point 6

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 28 Jan 2017
Convert to latex point 7
