### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by drg1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#25]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by bbp1002** [comment]
![image](https://user-images.githubusercontent.com/74184979/99780689-1adf0e00-2b17-11eb-8ed9-46d8e6f2ec70.png)
https://medium.com/@ferrand.d/can-you-and-should-you-use-vector-drawables-a-cheatsheet-32a2e1cc2ecf#.eoek6mlry

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Fix exception with vectors in API < 21 #25
