### ISSUE TITLE
Imprimir memoria

### ISSUE THREAD

**Issue by drg1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#34]
La memoria ha de estar encuadernada en formato:

Libro cosido,
Libro pegado,
Libro con grapa de canto metálico prensada.
Revista de tapa dura y grapa.
No se deben usar formatos de encuadernación de tornillos, espirales, canutillos y similares.

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Finish report #34
