### ISSUE TITLE
Manual del programador

### ISSUE THREAD

**Issue by drg1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#36]
- Instalación Android Studio
- Importación del proyecto
- Estructura directorios
- Ejecución tests en local
- Servicios de integración continua
- Creación de un ejecutable
- Plataforma de desarrollo del algoritmo
- Plataforma de conteo

**Comment by jfm1006** [comment]
changed the pipeline from TODO to Backlog for Untitled - 167943 - 2016-08-17 on 24 Jan 2017

**Comment by jfm1006** [comment]
changed the pipeline from Backlog to In Progress for Untitled - 167943 - 2016-08-17 on 3 Feb 2017

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 3 Feb 2017
Add javadoc

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 5 Feb 2017
Document Manual Programador
