### ISSUE TITLE
Pasar anexos a latex

### ISSUE THREAD

**Issue by drg1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#37]
**Anexos**
- [x]  Plan del proyecto software
- [x]  Especificación de Requisitos
- [x]  Especificación de diseño
- [x]  Manual del programador
- [x]  Manual de usuario

Expresión regular para corregir las referencias:

- Buscar: (\{\[\})([\w:\\]+)(\{\]\}\\\_)
- Reemplazar por: \\citep{\2}

Ej: {[}art:campbell2005{]}\_ -> \citep{art:campbell2005}

Expresión regular para corregir las imágenes:

- Buscar: (\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})
- Reemplazar por: \\imagen{\2}{descripción...}

Ej: \includegraphics{../../img/s2.png} -> \imagen{s2}{descripción...}}

**Comment by jfm1006** [comment]
changed the pipeline from New Issues to TODO for Untitled - 167943 - 2016-08-17 on 28 Jan 2017

**Comment by jfm1006** [comment]
changed the pipeline from TODO to Backlog for Untitled - 167943 - 2016-08-17 on 4 Feb 2017

**Comment by jfm1006** [comment]
changed the pipeline from Backlog to In Progress for Untitled - 167943 - 2016-08-17 on 5 Feb 2017

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 6 Feb 2017
Convert annex D to latex

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 6 Feb 2017
Convert annex E to latex

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 7 Feb 2017
Convert annex B to latex
