### ISSUE TITLE
Grabar discos

### ISSUE THREAD

**Issue by drg1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#39]
- Código fuente app
- Ejecutable app
- Herramientas
  - Plataforma de desarrollo del algoritmo
  - Herramienta de conteo de abejas
- Documentación
  - Memoria
  - Anexos
  - JavaDoc

- Dataset de videos

**README**

- Repositorio GoBees
- Repositorio prototipos
- Repositorio dependencia OpenCV

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 1 Feb 2017
Add cd cover

**Comment by jfm1006** [comment]
added a commit that referenced this issue on 1 Feb 2017
Add cd cover

**Comment by jfm1006** [comment]
changed the pipeline from TODO to In Progress for Untitled - 167943 - 2016-08-17 on 8 Feb 2017
