### ISSUE TITLE
Crear página web

### ISSUE THREAD

**Issue by drg1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#41]
https://startbootstrap.com/template-overviews/new-age/
http://www.grabon.in/mobile-apps/

http://bronto.github.io/javasphinx/

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Add Google Play link #41

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Update .gitignore #41

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Finish website #41

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Minor fixes and compress imgs #41

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Minor changes #41

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Minor changes #41

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Add doc link #41

**Comment by bbp1002** [comment]
http://gobees.io/
