### ISSUE TITLE
Implementar splash screen

### ISSUE THREAD

**Issue by jfm1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#7]
En vez de dejar en blanco la pantalla mientras carga la app, mostrar una pantalla con el logo de la app.
https://www.bignerdranch.com/blog/splash-screens-the-right-way/
https://material.io/guidelines/patterns/launch-screens.html

**Comment by drg1006** [comment]
Se añade un commit que referencia a este issue.
Add splash activity #7
