### ISSUE TITLE
Integración de SonarQube

### ISSUE THREAD

**Issue by jfm1006** [jfm1006/GESPRO_PracticaGestionTareas_2021#8]
Aunque ya se cuenta con code climate y codecov entre los servicios de integración continua para evaluar la calidad del código, sería recomendable pasar también los motores de análisis de SonarQube ya que es el que utilizará el tribunal para evaluar el TFG.

https://sonarqube.com/
https://github.com/integrations/sonarqube
https://docs.travis-ci.com/user/sonarqube/

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Integrate SonarQube #8

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Minor fix SonarQube #8

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Minor fixes #8

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Minor fixes #8

**Comment by bbp1002** [comment]
Se añade un commit que referencia esta issue.
Finish SonarQube #8
